package com.cloud.apim.otoroshi.extensions.waf.entities

import com.cloud.apim.otoroshi.extensions.waf.bots.{BotCatalog, BotSignature}
import com.cloud.apim.otoroshi.extensions.waf.security.{SecurityDatastores, SecurityState}
import otoroshi.api.*
import otoroshi.env.Env
import otoroshi.models.*
import otoroshi.next.extensions.*
import otoroshi.security.IdGenerator
import otoroshi.storage.*
import otoroshi.utils.syntax.implicits.*
import play.api.libs.json.*

import scala.util.{Failure, Success, Try}

/** What to do about one bot, or one whole category of them. */
final case class BotRule(target: String, action: String = "monitor", weight: Int = 0) {
  def json: JsValue = Json.obj("target" -> target, "action" -> action, "weight" -> weight)
  def matches(sig: BotSignature): Boolean = target.trim.toLowerCase match {
    case t if t.startsWith("name:")     => t.drop(5) == sig.name.toLowerCase
    case t if t.startsWith("category:") => t.drop(9) == sig.category.toLowerCase
    case "*"                            => true
    case other                          => other == sig.name.toLowerCase
  }
}

object BotRule {
  /**
   * No `challenge` here on purpose.
   *
   * There is one challenge implementation and it lives in the threat response engine. To challenge
   * a crawler, give it a weight that reaches a `challenge` tier in the threat policy — that way the
   * decision stays in one place and a bot rule cannot quietly mean something different from an
   * identical score coming from anywhere else.
   */
  val actions: Seq[String] = Seq("allow", "monitor", "deny")
  def read(json: JsValue): BotRule = BotRule(
    target = (json \ "target").asOpt[String].getOrElse("*"),
    action = (json \ "action").asOpt[String].getOrElse("monitor"),
    weight = (json \ "weight").asOpt[Int].getOrElse(0)
  )
  /** Nothing is denied by default: a policy that starts blocking crawlers on install is a trap. */
  val defaults: Seq[BotRule] = Seq(
    BotRule("category:search", "allow", 0),
    BotRule("category:monitoring", "allow", 0),
    BotRule("category:ai", "monitor", 0),
    BotRule("category:seo", "monitor", 10)
  )
}

/**
 * What the gateway does about automated clients.
 *
 * Two capabilities that share one catalog: proving that a crawler is who it claims to be, and
 * applying a policy to the ones that are — including the AI crawlers, where a `robots.txt` line is
 * a request and this is the enforcement.
 */
final case class BotPolicy(
    location: EntityLocation = EntityLocation.default,
    id: String,
    name: String,
    description: String = "",
    tags: Seq[String] = Seq.empty,
    metadata: Map[String, String] = Map.empty,
    enabled: Boolean = true,
    signatures: Seq[BotSignature] = BotCatalog.all,
    rules: Seq[BotRule] = BotRule.defaults,
    verifyKnownBots: Boolean = true,
    verifiedBypass: Boolean = true,
    impersonatorWeight: Int = 60,
    impersonatorAction: String = "deny",
    unknownBotWeight: Int = 0,
    denyStatus: Int = 403,
    robotsExtra: String = "",
    llmsTxt: String = ""
) extends EntityLocationSupport {

  override def internalId: String               = id
  override def json: JsValue                    = BotPolicy.format.writes(this)
  override def theName: String                  = name
  override def theDescription: String           = description
  override def theTags: Seq[String]             = tags
  override def theMetadata: Map[String, String] = metadata

  def signatureFor(userAgent: String): Option[BotSignature] = signatures.find(_.matches(userAgent))

  def ruleFor(sig: BotSignature): BotRule =
    rules.find(r => r.target.toLowerCase.startsWith("name:") && r.matches(sig))
      .orElse(rules.find(_.matches(sig)))
      .getOrElse(BotRule("*", "monitor", unknownBotWeight))

  /**
   * The robots.txt this policy actually enforces.
   *
   * Generated from the rules rather than written by hand, so the file and the gateway cannot drift
   * apart — which is the usual failure of a robots.txt nobody enforces.
   */
  def robotsTxt: String = {
    // anything denied outright, or weighted heavily enough that it will not get far
    val disallowed = signatures.filter { sig =>
      val rule = ruleFor(sig)
      rule.action.equalsIgnoreCase("deny") || rule.weight >= 50
    }
    val blocks = disallowed.flatMap { sig =>
      sig.uaContains.headOption.map(agent => s"User-agent: ${agent}\nDisallow: /")
    }
    val header =
      s"""# Generated by the Cloud APIM Security Suite from policy "$name".
         |# These rules are enforced at the gateway, not merely declared here.""".stripMargin
    (Seq(header) ++ blocks ++ Option(robotsExtra).map(_.trim).filter(_.nonEmpty)).mkString("\n\n") + "\n"
  }
}

object BotPolicy {

  val format: Format[BotPolicy] = new Format[BotPolicy] {
    override def writes(o: BotPolicy): JsValue = o.location.jsonWithKey ++ Json.obj(
      "id"                  -> o.id,
      "name"                -> o.name,
      "description"         -> o.description,
      "metadata"            -> o.metadata,
      "tags"                -> JsArray(o.tags.map(JsString.apply)),
      "enabled"             -> o.enabled,
      "signatures"          -> JsArray(o.signatures.map(_.json)),
      "rules"               -> JsArray(o.rules.map(_.json)),
      "verify_known_bots"   -> o.verifyKnownBots,
      "verified_bypass"     -> o.verifiedBypass,
      "impersonator_weight" -> o.impersonatorWeight,
      "impersonator_action" -> o.impersonatorAction,
      "unknown_bot_weight"  -> o.unknownBotWeight,
      "deny_status"         -> o.denyStatus,
      "robots_extra"        -> o.robotsExtra,
      "llms_txt"            -> o.llmsTxt
    )

    override def reads(json: JsValue): JsResult[BotPolicy] = Try {
      BotPolicy(
        location = otoroshi.models.EntityLocation.readFromKey(json),
        id = json.select("id").asString,
        name = json.select("name").asString,
        description = json.select("description").asOpt[String].getOrElse(""),
        metadata = json.select("metadata").asOpt[Map[String, String]].getOrElse(Map.empty),
        tags = json.select("tags").asOpt[Seq[String]].getOrElse(Seq.empty),
        enabled = json.select("enabled").asOpt[Boolean].getOrElse(true),
        signatures = json.select("signatures").asOpt[JsArray].map(_.value.toSeq.map(BotSignature.read)).getOrElse(BotCatalog.all),
        rules = json.select("rules").asOpt[JsArray].map(_.value.toSeq.map(BotRule.read)).getOrElse(BotRule.defaults),
        verifyKnownBots = json.select("verify_known_bots").asOpt[Boolean].getOrElse(true),
        verifiedBypass = json.select("verified_bypass").asOpt[Boolean].getOrElse(true),
        impersonatorWeight = json.select("impersonator_weight").asOpt[Int].getOrElse(60),
        impersonatorAction = json.select("impersonator_action").asOpt[String].getOrElse("deny"),
        unknownBotWeight = json.select("unknown_bot_weight").asOpt[Int].getOrElse(0),
        denyStatus = json.select("deny_status").asOpt[Int].getOrElse(403),
        robotsExtra = json.select("robots_extra").asOpt[String].getOrElse(""),
        llmsTxt = json.select("llms_txt").asOpt[String].getOrElse("")
      )
    } match {
      case Failure(ex)    => JsError(ex.getMessage)
      case Success(value) => JsSuccess(value)
    }
  }

  def template(env: Env): BotPolicy = BotPolicy(
    id = IdGenerator.namedId("bot-policy", env),
    name = "Bot policy",
    description = "Verify the crawlers that claim to be somebody, and decide what the rest may do"
  )

  def resource(env: Env, datastores: SecurityDatastores, states: SecurityState): Resource = {
    Resource(
      "BotPolicy",
      "bot-policies",
      "bot-policy",
      "waf.extensions.cloud-apim.com",
      ResourceVersion("v1", true, false, true),
      GenericResourceAccessApiWithState[BotPolicy](
        format = BotPolicy.format,
        clazz = classOf[BotPolicy],
        keyf = id => datastores.botPolicyDatastore.key(id),
        extractIdf = c => datastores.botPolicyDatastore.extractId(c),
        extractIdJsonf = json => json.select("id").asString,
        idFieldNamef = () => "id",
        tmpl = (_, _, _) => BotPolicy.template(env).json,
        canRead = true, canCreate = true, canUpdate = true, canDelete = true, canBulk = true,
        stateAll = () => states.allBotPolicies(),
        stateOne = id => states.botPolicy(id),
        stateUpdate = values => states.updateBotPolicies(values)
      )
    )
  }
}

trait BotPolicyDatastore extends BasicStore[BotPolicy]

class KvBotPolicyDatastore(extensionId: AdminExtensionId, redisCli: RedisLike, _env: Env)
    extends BotPolicyDatastore
    with RedisLikeStore[BotPolicy] {
  override def fmt: Format[BotPolicy]              = BotPolicy.format
  override def redisLike(using env: Env): RedisLike = redisCli
  override def key(id: String): String             = s"${_env.storageRoot}:extensions:${extensionId.cleanup}:botpolicies:$id"
  override def extractId(value: BotPolicy): String = value.id
}
