package com.cloud.apim.otoroshi.extensions.waf.tuning

import com.cloud.apim.otoroshi.extensions.waf.entities.{CloudApimWafConfig, WafRuleset}
import org.joda.time.DateTime
import play.api.libs.json.*

/** The entities a single "this was a false positive" has to create or change. */
final case class WritePlan(
    ruleset: WafRuleset,
    rulesetCreated: Boolean,
    config: Option[CloudApimWafConfig],
    entry: String
) {
  def json: JsValue = Json.obj(
    "ruleset_id"      -> ruleset.id,
    "ruleset_name"    -> ruleset.name,
    "ruleset_created" -> rulesetCreated,
    "config_updated"  -> config.isDefined,
    "entry"           -> entry
  )
}

/**
 * Where a generated exclusion goes, and what it says about itself once it is there.
 *
 * Two things this deliberately does not do. It does not append to whatever ruleset the config
 * happens to reference: those are shared, and a tuning decision taken for one route would silently
 * follow every other route that reuses the baseline. And it does not write inline rules on the
 * config: that field is hand-authored, and an assistant editing it turns every future manual change
 * into a merge.
 *
 * Instead each config gets up to two rulesets of its own, marked in metadata, ordered so the
 * mechanism in them can work — see [[Placement]]. They are ordinary entities: reviewable in the UI,
 * exportable, diffable, and deletable in one click if the whole session was a mistake.
 */
object ExclusionWriter {

  val ManagedKey: String = "cloud-apim.tuning.managed"
  val ConfigKey: String  = "cloud-apim.tuning.config"
  val Tag: String        = "cloud-apim-tuning"

  def rulesetName(config: CloudApimWafConfig, placement: Placement): String =
    s"${config.name} — exclusions (${placement.name} CRS)"

  /** The assistant's own ruleset for this config and position, if it has already made one. */
  def managed(config: CloudApimWafConfig, placement: Placement, all: Seq[WafRuleset]): Option[WafRuleset] =
    all.find { rs =>
      rs.metadata.get(ConfigKey).contains(config.id) && rs.metadata.get(ManagedKey).contains(placement.name)
    }

  /** A single `#` line cannot be escaped out of, so the text is flattened onto one. */
  private def comment(text: String): String =
    "# " + text.replace("\r", " ").replace("\n", " ").take(300)

  /**
   * The exclusion, with why it exists written next to it.
   *
   * A bare `SecRuleUpdateTargetById 942100 "!ARGS:comment"` six months later is indistinguishable
   * from a mistake, and the safest-looking thing to do with a line nobody can explain is to delete
   * it. The provenance is the difference between a reviewable decision and folklore.
   */
  def entry(
      seclang: String,
      ruleId: Int,
      target: Option[MatchedTarget],
      reason: String,
      by: String,
      route: Option[String],
      at: DateTime = DateTime.now()
  ): String = {
    val where = target.map(t => s" on ${t.full}").getOrElse("")
    Seq(
      comment(s"cloud-apim tuning · ${at.toString()} · by $by"),
      comment(s"false positive on rule $ruleId$where${route.map(r => s" · route $r").getOrElse("")}"),
      comment(s"reason: ${Option(reason).map(_.trim).filter(_.nonEmpty).getOrElse("not given")}"),
      seclang
    ).mkString("\n")
  }

  /**
   * What to persist, without persisting it.
   *
   * The config is returned only when its `rulesets` list actually has to change, so re-applying to
   * an already-wired config touches one entity instead of two.
   */
  def plan(
      config: CloudApimWafConfig,
      placement: Placement,
      all: Seq[WafRuleset],
      entry: String,
      newRulesetId: => String
  ): WritePlan = {
    val existing = managed(config, placement, all)
    val ruleset  = existing match {
      case Some(rs) => rs.copy(rules = rs.rules :+ entry)
      case None     =>
        WafRuleset(
          location = config.location,
          id = newRulesetId,
          name = rulesetName(config, placement),
          description =
            s"Exclusions generated by the tuning assistant for '${config.name}', evaluated ${placement.name} the rest of the ruleset.",
          tags = Seq(Tag),
          metadata = Map(ManagedKey -> placement.name, ConfigKey -> config.id),
          enabled = true,
          rules = Seq(entry)
        )
    }
    val wired   = wire(config.rulesets, ruleset.id, placement)
    WritePlan(
      ruleset = ruleset,
      rulesetCreated = existing.isEmpty,
      config = Option.when(wired != config.rulesets)(config.copy(rulesets = wired)),
      entry = entry
    )
  }

  /**
   * The reference in the position its mechanism requires.
   *
   * `before` has to precede everything it excludes and `after` has to follow it, so this moves an
   * already-present reference rather than assuming it is where it should be — a ruleset that was
   * reordered by hand would otherwise keep a placement that no longer holds.
   */
  def wire(current: Seq[String], rulesetId: String, placement: Placement): Seq[String] = {
    val without = current.filterNot(_ == rulesetId)
    placement match {
      case Placement.Before => rulesetId +: without
      case Placement.After  => without :+ rulesetId
    }
  }
}
